#!/bin/sh

OUTPUT="$(./bwping -r -1 -b 800 -s 500 -v 200000 localhost 2>&1)"
STATUS="$?"

echo "$OUTPUT"

if [ "$STATUS" = "0" ]; then
    exit 1
else
    ISSUES="$(echo "$OUTPUT" | grep -v "^bwping: invalid reporting period, should be non-negative$")"

    if [ "$ISSUES" != "" ]; then
        exit 1
    fi
fi

exit 0
