#!/bin/sh

for MODE in "-4" "-6"; do
    OUTPUT="$(./bwping "$MODE" -B localhost -I 0 -T 255 -r 1 -u 100000 -b 800 -s 500 -v 200000 localhost 2>&1)"
    STATUS="$?"

    echo "$OUTPUT"

    if [ "$STATUS" != "0" ]; then
        exit "$STATUS"
    else
        ISSUES="$(echo "$OUTPUT" | grep -v "^Target: " | grep -v "^Periodic: " | grep -v "^Total: pkts sent/rcvd: 400/400, volume sent/rcvd: 200000/200000 bytes, ")"

        if [ "$ISSUES" != "" ]; then
            exit 1
        fi
    fi
done

exit 0
