name: Analyze

on:
  push:
    branches: [ master ]
  schedule:
  - cron: '0 10 * * 6'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  security-events: write

jobs:
  clang:
    name: Clang Analyzer
    uses: ./.github/workflows/clang_analyzer.yml
  codeql:
    name: CodeQL Analyzer
    uses: ./.github/workflows/codeql.yml
  sonarcloud:
    name: SonarCloud Analyzer
    uses: ./.github/workflows/sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
