name: Clang Analyzer

on:
  workflow_call:

permissions: {}

jobs:
  clang:
    strategy:
      matrix:
        mmsg:
        - enable-mmsg
        - disable-mmsg
        bpf:
        - enable-bpf
        - disable-bpf
    name: Clang Analyzer (--${{ matrix.mmsg }} --${{ matrix.bpf }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get -y update
        sudo apt-get -y install autoconf automake clang-tools
    - name: Perform Clang analysis
      run: |
        autoreconf -f -i -Wall,error
        scan-build ./configure --${{ matrix.mmsg }} --${{ matrix.bpf }}
        scan-build --status-bugs -v -o scan-build-results make "CFLAGS=-std=c11 -Werror"
    - uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: clang-analysis-results-${{ matrix.mmsg }}-${{ matrix.bpf }}
        path: scan-build-results/
