name: "Coverity Analysis"

on:
  schedule:
  - cron: "0 13 * * 6"

jobs:
  coverity:
    name: "Coverity Analysis"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    env:
      PROJECT_NAME: oleg-derevenetz%2Fbwping
      NOTIFICATION_EMAIL: oleg-derevenetz@yandex.ru

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v2

    - name: "Install additional packages"
      run: |
        sudo apt-get update
        sudo apt-get -y install autoconf automake

    - name: "Initialize Coverity"
      env:
        COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
      run: |
        mkdir -p "$HOME/Coverity"
        wget https://scan.coverity.com/download/linux64 --post-data "token=$COVERITY_TOKEN&project=$PROJECT_NAME" -O "$HOME/Coverity/coverity_tool.tgz"
        tar -C "$HOME/Coverity" -xzf "$HOME/Coverity/coverity_tool.tgz"
        mv "$HOME/Coverity/cov-analysis-linux64-"* "$HOME/Coverity/cov-analysis-linux64"

    - name: "Run build via Coverity wrapper"
      run: |
        autoreconf -f -i -Wall,error
        ./configure
        "$HOME/Coverity/cov-analysis-linux64/bin/cov-build" --dir cov-int make

    - name: "Upload Coverity scan results"
      env:
        COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
      run: |
        tar -czf cov-int.tgz cov-int
        curl --form token="$COVERITY_TOKEN" \
             --form file=@cov-int.tgz \
             --form email="$NOTIFICATION_EMAIL" \
             --form version="$GITHUB_REF" \
             --form description="Automatic Coverity Scan build for $GITHUB_REF" "https://scan.coverity.com/builds?project=$PROJECT_NAME"
